import 'package:dropdown_search/dropdown_search.dart';
import 'package:flutter/material.dart';

class DropdownButtonProps extends IconButtonProps {
  const DropdownButtonProps({
    icon = const Icon(Icons.arrow_drop_down, size: 24),
    isVisible = true,
    iconSize = 24.0,
    visualDensity,
    padding = const EdgeInsets.all(8.0),
    alignment = Alignment.center,
    splashRadius,
    color,
    focusColor,
    hoverColor,
    highlightColor,
    splashColor,
    disabledColor,
    mouseCursor = SystemMouseCursors.click,
    focusNode,
    autofocus = false,
    tooltip,
    enableFeedback = false,
    constraints,
    style,
    isSelected,
    selectedIcon,
    onPressed,
  }) : super(
          icon: const Icon(Icons.arrow_drop_down, size: 24),
          isVisible: true,
          iconSize: 24.0,
          visualDensity: visualDensity,
          padding: const EdgeInsets.all(8.0),
          alignment: Alignment.center,
          splashRadius: splashRadius,
          color: color,
          focusColor: focusColor,
          hoverColor: hoverColor,
          highlightColor: highlightColor,
          splashColor: splashColor,
          disabledColor: disabledColor,
          mouseCursor: SystemMouseCursors.click,
          focusNode: focusNode,
          autofocus: false,
          tooltip: tooltip,
          enableFeedback: false,
          constraints: constraints,
          style: style,
          isSelected: isSelected,
          selectedIcon: selectedIcon,
          onPressed: onPressed,
        );
}
